config/routes.rb
MapDemo::Application.routes.draw do
  resources :houses

  get "home/map1"

  get "home/map2"

end

app/models/house.rb
class House < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  acts_as_gmappable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def map1
  end

  def map2
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  # GET /houses
  # GET /houses.json
  def index
    @houses = House.near("San Francisco, CA", 300, :order => :distance)
    @markers = @houses.to_gmaps4rails

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @houses }
    end
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
    @house = House.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @house }
    end
  end

  # GET /houses/new
  # GET /houses/new.json
  def new
    @house = House.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @house }
    end
  end

  # GET /houses/1/edit
  def edit
    @house = House.find(params[:id])
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(params[:house])

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render json: @house, status: :created, location: @house }
      else
        format.html { render action: "new" }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /houses/1
  # PUT /houses/1.json
  def update
    @house = House.find(params[:id])

    respond_to do |format|
      if @house.update_attributes(params[:house])
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house = House.find(params[:id])
    @house.destroy

    respond_to do |format|
      format.html { redirect_to houses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/home/map1.html.erb
<h1>Home#map1</h1>
<p>Find me in app/views/home/map1.html.erb</p>

<%#= gmaps({
  "direction" => {
    "data" => {"from" => "San Francisco, CA", "to" => "Omaha, NE"}
  }
}) %>

<%= gmaps({
    "map_options" => { "type" => "SATELLITE", "center_latitude" => 0, "center_longitude" => 180, "zoom" => 3, "auto_adjust" => true},
    "markers"     => { "data" => '[{ "description": "", "title": "", "lng": "5.9311119", "lat": "43.1251606", "picture": "", "width": "", "height": "" } ,{ "description": "", "title": "", "lng": "2.3509871", "lat": "48.8566667", "picture": "", "width": "", "height": "" } ]',
                                         },
    "polylines"   => { "data" => ' [ [
                         {"lng": -122.214897, "lat": 37.772323},
                         {"lng": -157.821856, "lat": 21.291982},
                         {"lng": 178.431, "lat": -18.142599},
                         {"lng": 153.027892, "lat": -27.46758}
                         ],
                         [
                         {"lng": -120.214897, "lat": 30.772323, "strokeColor": "#000", "strokeWeight" : 2 },
                         {"lng": -10.821856, "lat": 50.291982}
                         ] ]' },
     "polygons"    => { "data" => '[ [
                         {"lng": -80.190262, "lat": 25.774252},
                         {"lng": -66.118292, "lat": 18.466465},
                         {"lng": -64.75737, "lat": 32.321384}
                         ] ]' },
     "circles"     => { "data" => '[
                         {"lng": -122.214897, "lat": 37.772323, "radius": 1000000},
                         {"lng": 122.214897, "lat": 37.772323, "radius": 1000000, "strokeColor": "#FF0000"}
                         ]',
                                        },
     "direction"   => { "data"    => { "from" => "toulon, france", "to" => "paris, france"} ,
                        "options" => {"waypoints" => ["toulouse, france", "brest, france"], "travelMode" => "DRIVING", "display_panel" => true, "panel_id" => "instructions"}
 }
    })
    %>

app/views/home/map2.html.erb
<h1>Home#map2</h1>
<p>Find me in app/views/home/map2.html.erb</p>

app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @house.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing house</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<h1>Listing houses</h1>

<p><%= @markers %></p>

<%= gmaps({
  "direction" => {
    "data" => {"from" => "San Francisco, CA", "to" => "San Diego, CA"}
  },
  "markers" => {"data" => @markers}
}) %>

<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @houses.each do |house| %>
  <tr>
    <td><%= house.address %></td>
    <td><%= house.latitude %></td>
    <td><%= house.longitude %></td>
    <td><%= link_to 'Show', house %></td>
    <td><%= link_to 'Edit', edit_house_path(house) %></td>
    <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New house</h1>

<%= render 'form' %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @house.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @house.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @house.longitude %>
</p>


<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MapDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= content_for :scripts %>
</body>
</html>